<?php return array (
  'btn' => '#696969',
  'btn_text' => '#ffffff',
  'bg_page' => '#fafafa',
  'text_top' => '#ffffff',
  'link_top' => '#2dc4f0',
  'bg_top' => '',
  'text_head' => '#444444',
  'link_head' => '#2dc4f0',
  'bg_header' => '#ffffff',
  'text' => '#444444',
  'link' => '#2dc4f0',
  'bg_body' => '#ffffff',
  'text_foot' => '#444444',
  'link_foot' => '#2dc4f0',
  'bg_footer' => '#ededed',
  'text_bottom' => '#ffffff',
  'link_bottom' => '#2dc4f0',
  'bg_bottom' => '',
);